import { Product } from "../_interface/interface";

export const mockProducts: Product[] = [
    {
        id: 1,
        name: 'Khóa học ReactJS từ Cơ bản đến Nâng cao',
        slug: 'khoa-hoc-reactjs-tu-co-ban-den-nang-cao',
        price: 799000,
        shortDescription: 'Trở thành master ReactJS sau 30 ngày.',
        description: 'Khóa học này cung cấp kiến thức toàn diện về ReactJS, từ các khái niệm cơ bản như JSX, Components, State, Props cho đến các chủ đề nâng cao như Hooks, Context API, Redux, và tối ưu hiệu năng. Phù hợp cho người mới bắt đầu và cả lập trình viên đã có kinh nghiệm.',
        image: 'https://placehold.co/600x400/3498db/ffffff?text=ReactJS',
        rating: 4.8,
        category: 'Lập trình',
        curriculum: [
            { id: 'r1', title: 'Giới thiệu về React và JSX', duration: '15 phút' },
            { id: 'r2', title: 'Components, Props và State', duration: '30 phút' },
            { id: 'r3', title: 'Lifecycle Methods (Class Components)', duration: '25 phút' },
            { id: 'r4', title: 'React Hooks: useState và useEffect', duration: '45 phút' },
            { id: 'r5', title: 'Xử lý sự kiện và Form', duration: '30 phút' },
            { id: 'r6', title: 'React Router: Điều hướng trong ứng dụng', duration: '40 phút' },
            { id: 'r7', title: 'Quản lý state với Context API', duration: '35 phút' },
            { id: 'r8', title: 'Giới thiệu về Redux', duration: '50 phút' },
            { id: 'r9', title: 'Tối ưu hiệu năng với useMemo và useCallback', duration: '30 phút' },
        ],
    },
    {
        id: 2,
        name: 'Tiếng Anh Giao tiếp cho người đi làm',
        slug: 'tieng-anh-giao-tiep-cho-nguoi-di-lam',
        price: 1250000,
        shortDescription: 'Tự tin giao tiếp tiếng Anh trong môi trường công sở.',
        description: 'Chương trình học được thiết kế đặc biệt cho người đi làm, tập trung vào các tình huống giao tiếp thực tế như họp, thuyết trình, viết email, và trò chuyện với đồng nghiệp. Giáo viên bản ngữ giàu kinh nghiệm.',
        image: 'https://placehold.co/600x400/2ecc71/ffffff?text=English',
        rating: 4.9,
        category: 'Ngoại ngữ',
        curriculum: [
            { id: 'e1', title: 'Bài 1: Chào hỏi và giới thiệu bản thân', duration: '20 phút' },
            { id: 'e2', title: 'Bài 2: Giao tiếp qua điện thoại', duration: '25 phút' },
            { id: 'e3', title: 'Bài 3: Tham gia một cuộc họp', duration: '35 phút' },
            { id: 'e4', title: 'Bài 4: Thuyết trình và trình bày ý tưởng', duration: '40 phút' },
            { id: 'e5', title: 'Bài 5: Viết email chuyên nghiệp', duration: '30 phút' },
        ],
    },
    {
        id: 3,
        name: 'Thiết kế UI/UX cho người mới bắt đầu',
        slug: 'thiet-ke-ui-ux-cho-nguoi-moi-bat-dau',
        price: 450000,
        shortDescription: 'Học cách tạo ra các giao diện đẹp và thân thiện.',
        description: 'Khóa học này sẽ dẫn dắt bạn qua quy trình thiết kế một sản phẩm số, từ nghiên cứu người dùng, xây dựng wireframe, prototype cho đến thiết kế giao diện hoàn chỉnh bằng Figma. Không yêu cầu kinh nghiệm trước.',
        image: 'https://placehold.co/600x400/9b59b6/ffffff?text=UI/UX',
        rating: 4.7,
        category: 'Thiết kế',
        curriculum: [
            { id: 'd1', title: 'Nguyên tắc cơ bản trong thiết kế UI', duration: '30 phút' },
            { id: 'd2', title: 'Nghiên cứu người dùng và xây dựng Persona', duration: '45 phút' },
            { id: 'd3', title: 'Wireframing và Prototyping với Figma', duration: '60 phút' },
            { id: 'd4', title: 'Lý thuyết màu sắc và Typography', duration: '40 phút' },
            { id: 'd5', title: 'Thiết kế Responsive cho nhiều thiết bị', duration: '50 phút' },
        ],
    },
    {
        id: 4,
        name: 'Khóa học Python cho Khoa học Dữ liệu',
        slug: 'khoa-hoc-python-cho-khoa-hoc-du-lieu',
        price: 999000,
        shortDescription: 'Làm chủ Python và các thư viện phân tích dữ liệu.',
        description: 'Học sâu về Python và các thư viện mạnh mẽ như NumPy, Pandas, Matplotlib, và Scikit-learn để xử lý, phân tích, và trực quan hóa dữ liệu. Xây dựng các mô hình học máy cơ bản.',
        image: 'https://placehold.co/600x400/f1c40f/ffffff?text=Python',
        rating: 4.8,
        category: 'Lập trình',
        curriculum: [
            { id: 'p1', title: 'Giới thiệu Python và môi trường làm việc', duration: '20 phút' },
            { id: 'p2', title: 'Thư viện NumPy', duration: '45 phút' },
            { id: 'p3', title: 'Thư viện Pandas', duration: '60 phút' },
            { id: 'p4', title: 'Trực quan hóa dữ liệu với Matplotlib & Seaborn', duration: '50 phút' },
        ],
    },
    {
        id: 5,
        name: 'Marketing trên mạng xã hội 2025',
        slug: 'marketing-tren-mang-xa-hoi-2025',
        price: 600000,
        shortDescription: 'Chiến lược marketing hiệu quả trên Facebook, Instagram, TikTok.',
        description: 'Cập nhật những xu hướng và thuật toán mới nhất của các nền tảng mạng xã hội. Học cách xây dựng nội dung viral, chạy quảng cáo tối ưu và phân tích hiệu quả chiến dịch.',
        image: 'https://placehold.co/600x400/e67e22/ffffff?text=Marketing',
        rating: 4.6,
        category: 'Kinh doanh',
        curriculum: [
            { id: 'm1', title: 'Tổng quan về Social Media Marketing', duration: '15 phút' },
            { id: 'm2', title: 'Xây dựng chiến lược nội dung', duration: '40 phút' },
            { id: 'm3', title: 'Facebook & Instagram Ads', duration: '50 phút' },
            { id: 'm4', title: 'TikTok Marketing', duration: '35 phút' },
        ],
    },
    {
        id: 6,
        name: 'Luyện thi IELTS 7.0+',
        slug: 'luyen-thi-ielts-7-0',
        price: 2500000,
        shortDescription: 'Lộ trình chi tiết chinh phục band điểm 7.0 IELTS.',
        description: 'Chương trình học toàn diện 4 kỹ năng Nghe, Nói, Đọc, Viết. Cung cấp chiến thuật làm bài, bộ đề thi thử sát với thực tế và được chấm chữa chi tiết bởi các chuyên gia IELTS.',
        image: 'https://placehold.co/600x400/1abc9c/ffffff?text=IELTS',
        rating: 4.9,
        category: 'Ngoại ngữ',
        curriculum: [
            { id: 'i1', title: 'Chiến thuật làm bài Reading', duration: '60 phút' },
            { id: 'i2', title: 'Các dạng bài trong Writing Task 2', duration: '75 phút' },
            { id: 'i3', title: 'Luyện tập Speaking Part 1 & 2', duration: '50 phút' },
            { id: 'i4', title: 'Mẹo làm bài thi Listening', duration: '45 phút' },
        ],
    },
    {
        id: 7,
        name: 'Node.js & Express: Xây dựng API chuyên nghiệp',
        slug: 'nodejs-express-xay-dung-api-chuyen-nghiep',
        price: 850000,
        shortDescription: 'Học cách xây dựng backend mạnh mẽ với Node.js.',
        description: 'Khóa học tập trung vào việc xây dựng các RESTful API hiệu quả và an toàn bằng Node.js và Express. Bao gồm các chủ đề về xác thực, middleware, kết nối cơ sở dữ liệu (MongoDB) và triển khai ứng dụng.',
        image: 'https://placehold.co/600x400/34495e/ffffff?text=Node.js',
        rating: 4.8,
        category: 'Lập trình',
        curriculum: [
            { id: 'n1', title: 'Giới thiệu Node.js và NPM', duration: '20 phút' },
            { id: 'n2', title: 'Xây dựng server đầu tiên với Express', duration: '35 phút' },
            { id: 'n3', title: 'RESTful API và Middleware', duration: '45 phút' },
            { id: 'n4', title: 'Kết nối MongoDB với Mongoose', duration: '50 phút' },
        ],
    },
    {
        id: 8,
        name: 'Quản lý dự án với Agile và Scrum',
        slug: 'quan-ly-du-an-voi-agile-va-scrum',
        price: 1100000,
        shortDescription: 'Nâng cao hiệu suất đội nhóm với phương pháp Agile.',
        description: 'Hiểu rõ về triết lý Agile và framework Scrum. Học cách áp dụng các vai trò, sự kiện, và công cụ của Scrum để quản lý dự án một cách linh hoạt, hiệu quả và minh bạch.',
        image: 'https://placehold.co/600x400/e67e22/ffffff?text=Agile',
        rating: 4.7,
        category: 'Kinh doanh',
        curriculum: [
            { id: 'a1', title: 'Giới thiệu về Agile và Scrum', duration: '30 phút' },
            { id: 'a2', title: 'Các vai trò trong Scrum: PO, SM, Dev Team', duration: '40 phút' },
            { id: 'a3', title: 'Các sự kiện: Sprint Planning, Daily Scrum, Sprint Review', duration: '50 phút' },
            { id: 'a4', title: 'Quản lý Product Backlog và User Story', duration: '45 phút' },
        ],
    },
    {
        id: 9,
        name: 'Vue.js 3 Toàn tập',
        slug: 'vuejs-3-toan-tap',
        price: 750000,
        shortDescription: 'Xây dựng ứng dụng hiện đại với Vue 3 và Composition API.',
        description: 'Khóa học đi sâu vào Vue 3, bao gồm Composition API, Teleport, Fragments và cách tích hợp với TypeScript để xây dựng các ứng dụng lớn, dễ bảo trì.',
        image: 'https://placehold.co/600x400/41B883/ffffff?text=Vue.js',
        rating: 4.8,
        category: 'Lập trình',
        curriculum: [
            { id: 'v1', title: 'Khởi tạo dự án Vue 3', duration: '20 phút' },
            { id: 'v2', title: 'Tìm hiểu Composition API', duration: '50 phút' },
            { id: 'v3', title: 'Vue Router cho Vue 3', duration: '40 phút' },
            { id: 'v4', title: 'Quản lý state với Pinia', duration: '45 phút' },
        ],
    },
    {
        id: 10,
        name: 'DevOps Essentials: CI/CD với Jenkins và Docker',
        slug: 'devops-essentials-ci-cd-voi-jenkins-va-docker',
        price: 1500000,
        shortDescription: 'Tự động hóa quy trình phát triển và triển khai.',
        description: 'Học cách thiết lập một pipeline CI/CD hoàn chỉnh sử dụng Docker để đóng gói ứng dụng và Jenkins để tự động hóa việc build, test và deploy.',
        image: 'https://placehold.co/600x400/0db7ed/ffffff?text=DevOps',
        rating: 4.9,
        category: 'Lập trình',
        curriculum: [
            { id: 'do1', title: 'Giới thiệu DevOps và CI/CD', duration: '25 phút' },
            { id: 'do2', title: 'Làm việc với Docker', duration: '60 phút' },
            { id: 'do3', title: 'Cài đặt và cấu hình Jenkins', duration: '50 phút' },
            { id: 'do4', title: 'Xây dựng pipeline đầu tiên', duration: '70 phút' },
        ],
    }
];